CREATE DATABASE IF NOT EXISTS cadastrodb;

ALTER DATABASE cadastrodb
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON cadastrodb.* TO 'user@%' IDENTIFIED BY 'user';
